package sources.generateurmot.ihm;

import sources.generateurmot.Controleur;

/**
	* Classe FrameDictionnaireMot avec Apache NetBeans IDE 12.0
	* @author 	: -
	* @version 	: 1.0
*/

public class FrameDictionnaireMot extends javax.swing.JFrame {
	
	/**
		* Définition du serialVersionUID
	*/
	private static final long serialVersionUID = 1L;
	
	/**
		 * L'attribut renseigne sur le PanelFond.
	*/
	private PanelFond panelFond;
	
	/**
		* Construcuteur FrameDictionnaireMot
		* @param ctrl : Le contrôleur.
	*/
	public FrameDictionnaireMot(Controleur ctrl) 
	{
		// Initialisation des composants
		initComponents();
		
		// Création du composant
		this.panelFond = new PanelFond(ctrl);
		
		// Positionnement du composant sur la JFrame
		this.add( this.panelFond );
		
		// Affiche la JFrame
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked") 
	private void initComponents() 
	{
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Generateur de mot");
		setBackground(new java.awt.Color(51, 55, 55));
		setMinimumSize(new java.awt.Dimension(600, 600));
		setName("FrameDictionnaireMot"); // NOI18N

		setSize(new java.awt.Dimension(720, 510));
		setLocationRelativeTo(null);
	}
	
	// Variables declaration - do not modify					 
	// End of variables declaration				
}

