package sources.generateurmot.ihm;
		
import sources.generateurmot.Controleur;

/**
	* Classe PanelFond avec Apache NetBeans IDE 12.0
	* @author 	: -
	* @version 	: 1.0
*/

public class PanelFond extends javax.swing.JPanel {
	
	/**
		* Définition du serialVersionUID
	*/
	private static final long serialVersionUID = 1L;
	
	/**
		* L'attribut renseigne sur le Controleur.
	*/
	private Controleur ctrl;
	
	/**
		* Construcuteur PanelFond
		* @param ctrl : Le contrôleur.
	*/
	public PanelFond(Controleur ctrl) 
	{
		this.ctrl = ctrl;  // Instanciation du contrôleur pour l'interaction de l'évènement du bouton valider
		initComponents();  // Initialisation des composants
		
		this.textAreaTexteSaisie.setText("ABC");
		this.textAreaTexteCopier.setEditable(false);
	}

	/**
		* This method is called from within the constructor to initialize the form.
		* WARNING: Do NOT modify this code. The content of this method is always
		* regenerated by the Form Editor.
		*/
	@SuppressWarnings("unchecked")
	private void initComponents() 
	{
		panelNord = new javax.swing.JPanel();
		panelNordGauche = new javax.swing.JPanel();
		panelNordDroite = new javax.swing.JPanel();
		panelNordCentreTitre = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		panelSud = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		panelCentre = new javax.swing.JPanel();
		panelCentreNord = new javax.swing.JPanel();
		lblTexte = new javax.swing.JLabel();
		panelCentreCentre = new javax.swing.JPanel();
		panelCentreCentreCentreHaut = new javax.swing.JPanel();
		panelCentreCentreCentreGauche = new javax.swing.JPanel();
		panelCentreCentreCentreDroit = new javax.swing.JPanel();
		btnValider = new javax.swing.JButton();
		btnNettoyer = new javax.swing.JButton();
		panelCentreCentreCentreTxtArea = new javax.swing.JScrollPane();
		textAreaTexteSaisie = new javax.swing.JTextArea();
		panelCentreCentreCentreSud = new javax.swing.JPanel();
		panelCentreCentreCentreBas = new javax.swing.JPanel();
		panelCentreCentreCentreBasNord = new javax.swing.JPanel();
		panelCentreCentreCentreBasGauche = new javax.swing.JPanel();
		panelCentreCentreCentreBasDroit = new javax.swing.JPanel();
		panelCentreCentreCentreBasSud = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		textAreaTexteCopier = new javax.swing.JTextArea();

		setBackground(new java.awt.Color(51, 51, 51));
		setForeground(new java.awt.Color(255, 255, 255));
		setLayout(new java.awt.BorderLayout());

		panelNord.setBackground(new java.awt.Color(40, 40, 40));
		panelNord.setPreferredSize(new java.awt.Dimension(350, 100));
		panelNord.setLayout(new java.awt.BorderLayout());

		panelNordGauche.setBackground(new java.awt.Color(35, 35, 35));
		panelNordGauche.setPreferredSize(new java.awt.Dimension(180, 100));

		javax.swing.GroupLayout panelNordGaucheLayout = new javax.swing.GroupLayout(panelNordGauche);
		panelNordGauche.setLayout(panelNordGaucheLayout);
		panelNordGaucheLayout.setHorizontalGroup(
			panelNordGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 180, Short.MAX_VALUE)
		);
		panelNordGaucheLayout.setVerticalGroup(
			panelNordGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 100, Short.MAX_VALUE)
		);

		panelNord.add(panelNordGauche, java.awt.BorderLayout.LINE_START);

		panelNordDroite.setBackground(new java.awt.Color(35, 35, 35));
		panelNordDroite.setPreferredSize(new java.awt.Dimension(180, 100));

		javax.swing.GroupLayout panelNordDroiteLayout = new javax.swing.GroupLayout(panelNordDroite);
		panelNordDroite.setLayout(panelNordDroiteLayout);
		panelNordDroiteLayout.setHorizontalGroup(
			panelNordDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 180, Short.MAX_VALUE)
		);
		panelNordDroiteLayout.setVerticalGroup(
			panelNordDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 100, Short.MAX_VALUE)
		);

		panelNord.add(panelNordDroite, java.awt.BorderLayout.LINE_END);

		panelNordCentreTitre.setBackground(new java.awt.Color(35, 35, 35));
		panelNordCentreTitre.setLayout(new java.awt.BorderLayout());

		jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(220, 220, 220));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Générateur de Mot");
		panelNordCentreTitre.add(jLabel1, java.awt.BorderLayout.CENTER);

		panelNord.add(panelNordCentreTitre, java.awt.BorderLayout.CENTER);

		add(panelNord, java.awt.BorderLayout.PAGE_START);

		panelSud.setBackground(new java.awt.Color(35, 35, 35));
		panelSud.setPreferredSize(new java.awt.Dimension(100, 55));
		panelSud.setLayout(new java.awt.BorderLayout());

		jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(220, 220, 220));
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("version 1.0");
		panelSud.add(jLabel2, java.awt.BorderLayout.CENTER);

		add(panelSud, java.awt.BorderLayout.PAGE_END);

		panelCentre.setBackground(new java.awt.Color(51, 55, 55));
		panelCentre.setLayout(new java.awt.BorderLayout());

		panelCentreNord.setBackground(new java.awt.Color(50, 50, 50));
		panelCentreNord.setPreferredSize(new java.awt.Dimension(595, 50));
		panelCentreNord.setLayout(new java.awt.BorderLayout());

		lblTexte.setBackground(new java.awt.Color(50, 50, 50));
		lblTexte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
		lblTexte.setForeground(new java.awt.Color(220, 220, 220));
		lblTexte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblTexte.setText("Entrer votre texte");
		lblTexte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		panelCentreNord.add(lblTexte, java.awt.BorderLayout.CENTER);

		panelCentre.add(panelCentreNord, java.awt.BorderLayout.PAGE_START);

		panelCentreCentre.setBackground(new java.awt.Color(45, 51, 55));
		panelCentreCentre.setLayout(new java.awt.GridLayout(2, 1));

		panelCentreCentreCentreHaut.setBackground(new java.awt.Color(45, 45, 45));
		panelCentreCentreCentreHaut.setLayout(new java.awt.BorderLayout());

		panelCentreCentreCentreGauche.setBackground(new java.awt.Color(50, 50, 50));

		javax.swing.GroupLayout panelCentreCentreCentreGaucheLayout = new javax.swing.GroupLayout(panelCentreCentreCentreGauche);
		panelCentreCentreCentreGauche.setLayout(panelCentreCentreCentreGaucheLayout);
		panelCentreCentreCentreGaucheLayout.setHorizontalGroup(
			panelCentreCentreCentreGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 100, Short.MAX_VALUE)
		);
		panelCentreCentreCentreGaucheLayout.setVerticalGroup(
			panelCentreCentreCentreGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 114, Short.MAX_VALUE)
		);

		panelCentreCentreCentreHaut.add(panelCentreCentreCentreGauche, java.awt.BorderLayout.LINE_START);

		panelCentreCentreCentreDroit.setBackground(new java.awt.Color(50, 50, 50));
		panelCentreCentreCentreDroit.setPreferredSize(new java.awt.Dimension(100, 100));

		btnValider.setBackground(new java.awt.Color(50, 50, 50));
		btnValider.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		btnValider.setForeground(new java.awt.Color(220, 220, 220));
		btnValider.setText("Valider");
		btnValider.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnValiderActionPerformed(evt);
			}
		});
		panelCentreCentreCentreDroit.add(btnValider);

		btnNettoyer.setBackground(new java.awt.Color(50, 50, 50));
		btnNettoyer.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		btnNettoyer.setForeground(new java.awt.Color(220, 220, 220));
		btnNettoyer.setText("Nettoyer");
		btnNettoyer.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnNettoyerActionPerformed(evt);
			}
		});
		panelCentreCentreCentreDroit.add(btnNettoyer);

		panelCentreCentreCentreHaut.add(panelCentreCentreCentreDroit, java.awt.BorderLayout.LINE_END);

		panelCentreCentreCentreTxtArea.setBackground(new java.awt.Color(75, 75, 75));

		textAreaTexteSaisie.setBackground(new java.awt.Color(150, 150, 150));
		textAreaTexteSaisie.setColumns(20);
		textAreaTexteSaisie.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
		textAreaTexteSaisie.setForeground(new java.awt.Color(50, 50, 50));
		textAreaTexteSaisie.setRows(5);
		panelCentreCentreCentreTxtArea.setViewportView(textAreaTexteSaisie);

		panelCentreCentreCentreHaut.add(panelCentreCentreCentreTxtArea, java.awt.BorderLayout.CENTER);

		panelCentreCentreCentreSud.setBackground(new java.awt.Color(50, 50, 50));
		panelCentreCentreCentreSud.setPreferredSize(new java.awt.Dimension(595, 10));

		javax.swing.GroupLayout panelCentreCentreCentreSudLayout = new javax.swing.GroupLayout(panelCentreCentreCentreSud);
		panelCentreCentreCentreSud.setLayout(panelCentreCentreCentreSudLayout);
		panelCentreCentreCentreSudLayout.setHorizontalGroup(
			panelCentreCentreCentreSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 677, Short.MAX_VALUE)
		);
		panelCentreCentreCentreSudLayout.setVerticalGroup(
			panelCentreCentreCentreSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 10, Short.MAX_VALUE)
		);

		panelCentreCentreCentreHaut.add(panelCentreCentreCentreSud, java.awt.BorderLayout.PAGE_END);

		panelCentreCentre.add(panelCentreCentreCentreHaut);

		panelCentreCentreCentreBas.setBackground(new java.awt.Color(80, 80, 80));
		panelCentreCentreCentreBas.setLayout(new java.awt.BorderLayout());

		panelCentreCentreCentreBasNord.setBackground(new java.awt.Color(50, 50, 50));
		panelCentreCentreCentreBasNord.setPreferredSize(new java.awt.Dimension(595, 20));

		javax.swing.GroupLayout panelCentreCentreCentreBasNordLayout = new javax.swing.GroupLayout(panelCentreCentreCentreBasNord);
		panelCentreCentreCentreBasNord.setLayout(panelCentreCentreCentreBasNordLayout);
		panelCentreCentreCentreBasNordLayout.setHorizontalGroup(
			panelCentreCentreCentreBasNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 677, Short.MAX_VALUE)
		);
		panelCentreCentreCentreBasNordLayout.setVerticalGroup(
			panelCentreCentreCentreBasNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 20, Short.MAX_VALUE)
		);

		panelCentreCentreCentreBas.add(panelCentreCentreCentreBasNord, java.awt.BorderLayout.PAGE_START);

		panelCentreCentreCentreBasGauche.setBackground(new java.awt.Color(50, 50, 50));
		panelCentreCentreCentreBasGauche.setPreferredSize(new java.awt.Dimension(130, 119));

		javax.swing.GroupLayout panelCentreCentreCentreBasGaucheLayout = new javax.swing.GroupLayout(panelCentreCentreCentreBasGauche);
		panelCentreCentreCentreBasGauche.setLayout(panelCentreCentreCentreBasGaucheLayout);
		panelCentreCentreCentreBasGaucheLayout.setHorizontalGroup(
			panelCentreCentreCentreBasGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 130, Short.MAX_VALUE)
		);
		panelCentreCentreCentreBasGaucheLayout.setVerticalGroup(
			panelCentreCentreCentreBasGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 84, Short.MAX_VALUE)
		);

		panelCentreCentreCentreBas.add(panelCentreCentreCentreBasGauche, java.awt.BorderLayout.LINE_START);

		panelCentreCentreCentreBasDroit.setBackground(new java.awt.Color(50, 50, 50));
		panelCentreCentreCentreBasDroit.setPreferredSize(new java.awt.Dimension(130, 119));

		javax.swing.GroupLayout panelCentreCentreCentreBasDroitLayout = new javax.swing.GroupLayout(panelCentreCentreCentreBasDroit);
		panelCentreCentreCentreBasDroit.setLayout(panelCentreCentreCentreBasDroitLayout);
		panelCentreCentreCentreBasDroitLayout.setHorizontalGroup(
			panelCentreCentreCentreBasDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 130, Short.MAX_VALUE)
		);
		panelCentreCentreCentreBasDroitLayout.setVerticalGroup(
			panelCentreCentreCentreBasDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 84, Short.MAX_VALUE)
		);

		panelCentreCentreCentreBas.add(panelCentreCentreCentreBasDroit, java.awt.BorderLayout.LINE_END);

		panelCentreCentreCentreBasSud.setBackground(new java.awt.Color(50, 50, 50));
		panelCentreCentreCentreBasSud.setPreferredSize(new java.awt.Dimension(595, 20));

		javax.swing.GroupLayout panelCentreCentreCentreBasSudLayout = new javax.swing.GroupLayout(panelCentreCentreCentreBasSud);
		panelCentreCentreCentreBasSud.setLayout(panelCentreCentreCentreBasSudLayout);
		panelCentreCentreCentreBasSudLayout.setHorizontalGroup(
			panelCentreCentreCentreBasSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 677, Short.MAX_VALUE)
		);
		panelCentreCentreCentreBasSudLayout.setVerticalGroup(
			panelCentreCentreCentreBasSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 20, Short.MAX_VALUE)
		);

		panelCentreCentreCentreBas.add(panelCentreCentreCentreBasSud, java.awt.BorderLayout.PAGE_END);

		textAreaTexteCopier.setBackground(new java.awt.Color(150, 150, 150));
		textAreaTexteCopier.setColumns(20);
		textAreaTexteCopier.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
		textAreaTexteCopier.setForeground(new java.awt.Color(50, 50, 50));
		textAreaTexteCopier.setRows(5);
		jScrollPane1.setViewportView(textAreaTexteCopier);

		panelCentreCentreCentreBas.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		panelCentreCentre.add(panelCentreCentreCentreBas);

		panelCentre.add(panelCentreCentre, java.awt.BorderLayout.CENTER);

		add(panelCentre, java.awt.BorderLayout.CENTER);
	}						
	
	/*--------------------------------------------------*/
	/*		L'ÉVÈNEMENT ACTION-LISTENER 		*/
	/*--------------------------------------------------*/
	
	/**
		* Si l'utilisateur clique sur le bouton valider
		* @param evt 
	*/
	private void btnValiderActionPerformed(java.awt.event.ActionEvent evt)
	{
		// Nettoyage du textAreaTexteCopier
		this.textAreaTexteCopier.setText( new String() );
		
		if ( evt.getSource() == this.btnValider )
		{
			// Récupère le texte saisie par l'utilisateur
			String texteEntree = this.textAreaTexteSaisie.getText();
			
			// Informe GenererMot qu'il faut générer le mot
			this.ctrl.genererMot(texteEntree);
			
			// Récupère le(s) mot(s) qui est/sont généré(s)
			this.textAreaTexteCopier.setText(this.ctrl.getMot());
		}
		
	}										  
	
	/**
		* Si l'utilisateur clique sur le bouton nettoyer
		* @param evt 
	*/
	private void btnNettoyerActionPerformed(java.awt.event.ActionEvent evt)
	{	
		if ( evt.getSource() == this.btnNettoyer )
		{
			// Nettoyage du textAreaTexteCopier
			this.textAreaTexteCopier.setText( new String() ); 
			this.ctrl.reinitMot();
		}
	}										   


	// Variables declaration - do not modify					 
	private javax.swing.JButton btnNettoyer;
	private javax.swing.JButton btnValider;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblTexte;
	private javax.swing.JPanel panelCentre;
	private javax.swing.JPanel panelCentreCentre;
	private javax.swing.JPanel panelCentreCentreCentreBas;
	private javax.swing.JPanel panelCentreCentreCentreBasDroit;
	private javax.swing.JPanel panelCentreCentreCentreBasGauche;
	private javax.swing.JPanel panelCentreCentreCentreBasNord;
	private javax.swing.JPanel panelCentreCentreCentreBasSud;
	private javax.swing.JPanel panelCentreCentreCentreDroit;
	private javax.swing.JPanel panelCentreCentreCentreGauche;
	private javax.swing.JPanel panelCentreCentreCentreHaut;
	private javax.swing.JPanel panelCentreCentreCentreSud;
	private javax.swing.JScrollPane panelCentreCentreCentreTxtArea;
	private javax.swing.JPanel panelCentreNord;
	private javax.swing.JPanel panelNord;
	private javax.swing.JPanel panelNordCentreTitre;
	private javax.swing.JPanel panelNordDroite;
	private javax.swing.JPanel panelNordGauche;
	private javax.swing.JPanel panelSud;
	private javax.swing.JTextArea textAreaTexteCopier;
	private javax.swing.JTextArea textAreaTexteSaisie;
	// End of variables declaration				   
}

